"""
WSGI config for carroll_classroom_analytics project.

It exposes the WSGI callable as a module-level variable named ``application``.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/howto/deployment/wsgi/
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'carroll_classroom_analytics.settings')

application = get_wsgi_application()
