# Generated by Django 5.0.1 on 2024-02-08 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('name', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('building', models.CharField(choices=[('CENG', 'Civil Engineering'), ('CHPL', 'All Saints Chapel'), ('CUBE', 'Cube'), ('EQCT', 'Equine Center'), ('FSCT', 'Fortin Science Center Labs'), ('GUAD', 'Guadalupe Hall'), ('HAC', 'Hunthausen Activity Center'), ('LYHS', ''), ('OCON', "O'Connell Hall"), ('OFCP', 'Off-Campus'), ('PCCC', 'Perkins Call Canine Center'), ('PECT', 'PE Center'), ('SIMP', 'Simperman Hall'), ('STCH', 'St. Charles Hall'), ('WBAR', 'Waterbarn')], max_length=4)),
                ('room_num', models.IntegerField()),
                ('occupancy', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_classroom', to='api.classroom')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_type', to='api.classroom')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instructor')),
            ],
        ),
    ]
