# Generated by Django 5.0.1 on 2024-03-26 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('building', models.CharField(choices=[('', ''), ('CENG', 'Civil Engineering'), ('CHPL', 'All Saints Chapel'), ('CUBE', 'Cube'), ('EQCT', 'Equine Center'), ('FSCT', 'Fortin Science Center Labs'), ('GUAD', 'Guadalupe Hall'), ('HAC', 'Hunthausen Activity Center'), ('OCON', "O'Connell Hall"), ('OFCP', 'Off-Campus'), ('PCCC', 'Perkins Call Canine Center'), ('PECT', 'PE Center'), ('SIMP', 'Simperman Hall'), ('STCH', 'St. Charles Hall'), ('WBAR', 'Waterbarn')], max_length=255)),
                ('room_num', models.CharField(max_length=255)),
                ('occupancy', models.FloatField(blank=True, default=None, null=True)),
                ('width', models.IntegerField(blank=True, default=None, null=True)),
                ('length', models.IntegerField(blank=True, default=None, null=True)),
                ('projector_num', models.IntegerField(blank=True, default=None, null=True)),
                ('features', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section_id', models.IntegerField()),
                ('course_num', models.CharField(max_length=255)),
                ('section_num', models.CharField(max_length=255)),
                ('term', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('min_credits', models.FloatField(null=True)),
                ('status', models.CharField(max_length=255)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('day', models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('th', 'Thursday'), ('MW', 'Monday, Wednesday'), ('MWF', 'Monday, Wednesday, Friday'), ('Tth', 'Tuesday, Thursday')], max_length=255)),
                ('instruction_method', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=255)),
                ('enrolled', models.IntegerField(null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.classroom')),
            ],
        ),
    ]
