# Generated by Django 5.0.1 on 2024-02-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='style',
            field=models.CharField(max_length=20),
        ),
    ]
