# Generated by Django 5.0.1 on 2024-04-28 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(db_column='instructor_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.instructor'),
        ),
    ]
