from django.apps import AppConfig

"""
Configures the API piece of the application, setting its name and the type of default primary key used when creating 
models.

Generated by 'django-admin startproject' using Django 5.0.1.
"""


class ApiConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'api'
